# Generated by Django 5.2.4 on 2026-03-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_devlog_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devlog',
            name='log_type',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10),
        ),
    ]
